# Generated by Django 5.2.3 on 2025-06-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_year',
            field=models.DateTimeField(),
        ),
    ]
