# Generated by Django 5.2.3 on 2025-07-02 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='film',
            name='status',
        ),
        migrations.RemoveField(
            model_name='series',
            name='current_episode',
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_year',
            field=models.IntegerField(default=1999),
        ),
        migrations.AlterField(
            model_name='series',
            name='next_release_date',
            field=models.CharField(choices=[('unknown', 'to be determined'), ('completed', 'finished airing')], default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='number_of_episodes',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='number_of_seasons',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispublic', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('null', 'not set'), ('plan', 'planned to watch'), ('watched', 'watched'), ('watching', 'watching')], default='null', max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('current_episode', models.IntegerField(blank=True, default=0, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.film')),
                ('userlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='watchlist.userlist')),
            ],
        ),
    ]
