# Generated by Django 5.2.3 on 2025-07-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='next_release_date',
        ),
    ]
