# Generated by Django 5.2.3 on 2025-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_userlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlistitem',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='film',
            name='release_year',
            field=models.IntegerField(default=1999),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('null', 'not set'), ('plan', 'planned to watch'), ('watched', 'watched'), ('watching', 'watching')], max_length=100),
        ),
    ]
