# Generated by Django 5.2.3 on 2025-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_rename_user_userlistitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_year',
            field=models.IntegerField(blank=True, default=1999),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(blank=True, choices=[('null', 'not set'), ('plan', 'planned to watch'), ('watched', 'watched'), ('watching', 'watching')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='current_episode',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='next_release_date',
            field=models.CharField(blank=True, choices=[('unknown', 'to be determined'), ('completed', 'finished airing')], default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='number_of_episodes',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='number_of_seasons',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
