# Generated by Django 5.2.3 on 2025-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_alter_film_rating_alter_film_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
