# Generated by Django 5.2.3 on 2025-06-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_alter_film_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_year',
            field=models.IntegerField(default=1999),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('null', 'not set'), ('plan', 'planned to watch'), ('watched', 'watched'), ('watching', 'watching')], max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='current_episode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='next_release_date',
            field=models.CharField(choices=[('unknown', 'to be determined'), ('completed', 'finished airing')], default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='number_of_episodes',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='number_of_seasons',
            field=models.IntegerField(default=2),
        ),
    ]
