# Generated by Django 5.2.3 on 2025-06-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0008_remove_userlistitem_user_userlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tmbd_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
