# Generated by Django 5.2.3 on 2025-06-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0009_film_tmbd_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='tmbd_id',
            new_name='tmdb_id',
        ),
    ]
