# Generated by Django 5.2.3 on 2025-06-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0010_rename_tmbd_id_film_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='film',
            name='status',
        ),
        migrations.RemoveField(
            model_name='series',
            name='current_episode',
        ),
        migrations.AddField(
            model_name='userlistitem',
            name='current_episode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userlistitem',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userlistitem',
            name='status',
            field=models.CharField(choices=[('null', 'not set'), ('plan', 'planned to watch'), ('watched', 'watched'), ('watching', 'watching')], default='null', max_length=100),
        ),
    ]
